# Generated by Django 5.0.1 on 2024-01-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0002_movie_celebrity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='celeb.celebrity'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.CharField(default='3/10/24', max_length=20),
        ),
    ]
