# Generated by Django 5.0.1 on 2024-01-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0003_rename_name_movie_title_remove_celebrity_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
