# Generated by Django 5.0.1 on 2024-01-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0004_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='age',
            field=models.DateField(),
        ),
    ]
