# Generated by Django 5.0.1 on 2024-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0006_alter_celebrity_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='celebrity',
            name='movies',
            field=models.ManyToManyField(related_name='celebs', to='celeb.movie'),
        ),
    ]
