# Generated by Django 5.0.1 on 2024-01-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0007_remove_movie_actors_celebrity_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
