# Generated by Django 5.0.1 on 2024-01-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0008_remove_movie_release_date_movie_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='celeb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='celeb.celebrity'),
        ),
    ]
