# Generated by Django 5.0.1 on 2024-01-19 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0009_remove_celebrity_movies_movie_celeb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='celeb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='celeb.celebrity'),
        ),
    ]
