# Generated by Django 5.0.1 on 2024-01-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0010_alter_movie_celeb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
