# Generated by Django 5.0.1 on 2024-01-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0012_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='letter',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
