# Generated by Django 5.0.1 on 2024-01-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0013_option_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='text',
        ),
    ]
